name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Run workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Optional: Run workflow on pull requests to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # Location of your HTML file in the repository
          output_location: "/"       # Location where the HTML file will be hosted